using BBDown.Core.Protobuf;
using BBDown.Core.Util;
using Google.Protobuf;
using System.Text;
using static BBDown.Core.Entity.Entity;
using System.Text.RegularExpressions;
using System.Text.Json;

namespace BBDown.Core.Util;

public static partial class SubUtil
{
    /// <summary>
    /// 构造字幕落盘路径：lan 来自接口响应（B 站/镜像站 EpHost/--insecure 下的中间人，
    /// 均为项目威胁模型内的外部输入），未净化直接拼路径可借 ..\ 或路径分隔符写出
    /// 工作目录（RF-18）。标题类文本统一走 GetValidFileName，此处对齐。
    /// </summary>
    private static string BuildSubtitlePath(string aid, string cid, string lan, string ext)
        => PathUtil.ResolveWorkPath($"{aid}/{aid}.{cid}.{PathUtil.GetValidFileName(lan)}.{ext}");

    //https://i0.hdslb.com/bfs/subtitle/subtitle_lan.json
    public static (string, string) GetSubtitleCode(string key)
    {
        // BCP-47 大小写规范化：语言子标签保持小写，连字符后的子标签按语义恢复标准大小写——
        // 地区子标签（2 字母，zh-tw/yue-hk/en-us）整体大写（zh-TW/yue-HK/en-US），
        // 其余（脚本标签 hans/hant、ai 前缀特例、数字/3+ 字母）首字母大写
        // （zh-Hans/zh-Hant、ai-Zh/ai-En）。原实现只把连字符后首个字母大写
        // （zh-tw→zh-Tw），匹配不上 switch 里的 zh-TW，小写输入的语言码会被
        // 错误标记为 und（Undetermined）。
        key = SubTagRegex().Replace(key, m =>
        {
            var sub = m.Groups[1].Value.ToLowerInvariant();
            if (sub.Length == 2)
                return "-" + sub.ToUpperInvariant();
            return "-" + char.ToUpperInvariant(sub[0]) + sub[1..];
        });

        return key switch
        {
            "ai-Zh" => ("chi", "中文（简体, AI识别）"),
            "ai-En" => ("eng", "English(generated by ai)"),
            "zh-CN" => ("chi", "中文（简体）"),
            "zh-HK" => ("chi", "中文（香港繁體）"),
            "zh-Hans" => ("chi", "中文（简体）"),
            "zh-TW" => ("chi", "中文（台灣繁體）"),
            "zh-Hant" => ("chi", "中文（繁體）"),
            "en-US" => ("eng", "English(USA)"),
            "ja" => ("jpn", "日本語"),
            "ko" => ("kor", "한국어"),
            "zh-SG" => ("chi", "中文（新加坡）"),
            "ab" => ("abk", "Аҳәынҭқарра"),
            "aa" => ("aar", "Qafár af"),
            "af" => ("afr", "Afrikaans"),
            "sq" => ("alb", "Gjuha shqipe"),
            "ase" => ("ase", "American Sign Language"),
            "am" => ("amh", "አማርኛ"),
            "arc" => ("arc", "ܐܪܡܝܐ"),
            "hy" => ("arm", "հայերեն"),
            "as" => ("asm", "অসমীয়া"),
            "ay" => ("aym", "Aymar aru"),
            "az" => ("aze", "Azərbaycan"),
            "bn" => ("ben", "বাংলা ভাষার"),
            "ba" => ("bak", "Башҡорттеле"),
            "eu" => ("baq", "Euskara"),
            "be" => ("bel", "беларуская мова biełaruskaja mova"),
            "bh" => ("bih", "Bihar"),
            "bi" => ("bis", "Bislama"),
            "bs" => ("bos", "босански"),
            "br" => ("bre", "Breton"),
            "bg" => ("bul", "български"),
            "yue" => ("chi", "粵語"),
            "yue-HK" => ("chi", "粵語（中國香港）"),
            "ca" => ("cat", "català"),
            "chr" => ("chr", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ"),
            "cho" => ("cho", "Chahta'"),
            "co" => ("cos", "lingua corsa"),
            "hr" => ("hrv", "Hrvatska"),
            "cs" => ("cze", "čeština"),
            "da" => ("dan", "Dansk"),
            "nl" => ("dut", "Nederlands"),
            "nl-BE" => ("dut", "Nederlands(Belgisch)"),
            "nl-NL" => ("dut", "Nederlands(Nederlands)"),
            "dz" => ("dzo", "རྫོང་ཁ།"),
            "en" => ("eng", "English"),
            "en-CA" => ("eng", "English(Canada)"),
            "en-IE" => ("eng", "English(Ireland)"),
            "en-GB" => ("eng", "English(UK)"),
            "eo" => ("epo", "Esperanto"),
            "et" => ("est", "Eestlane"),
            "fo" => ("fao", "føroyskt"),
            "fj" => ("fij", "Vakaviti"),
            "fil" => ("phi", "Pilipino"),
            "fi" => ("fin", "Suomi"),
            "fr" => ("fre", "Français"),
            "fr-BE" => ("fre", "Français(Belgique)"),
            "fr-CA" => ("fre", "Français(Canada)"),
            "fr-FR" => ("fre", "Français(La France)"),
            "fr-CH" => ("fre", "Français(Suisse)"),
            "ff" => ("ful", "Fulani"),
            "gl" => ("glg", "galego"),
            "ka" => ("geo", "ქართული ენა"),
            "de" => ("ger", "Deutsch"),
            "de-AT" => ("ger", "Deutsch(Österreich)"),
            "de-DE" => ("ger", "Deutsch(Deutschland)"),
            "de-CH" => ("ger", "Deutsch(Schweiz)"),
            "el" => ("gre", "Ελληνικά"),
            "kl" => ("kal", "Kalaallisut"),
            "gn" => ("grn", "avañe'ẽ"),
            "gu" => ("guj", "ગુજરાતી"),
            "hak" => ("hak", "Hak-kâ-fa"),
            "hak-TW" => ("hak", "Hak-kâ-fa"),
            "ha" => ("hau", "هَوُسَ"),
            "iw" => ("heb", "שפה עברית"),
            "hi" => ("hin", "हिन्दी"),
            "hi-Latn" => ("hin", "हिंदी(फोनेटिक)"),
            "hu" => ("hun", "Magyar"),
            "is" => ("ice", "icelandic"),
            "ig" => ("ibo", "Asụsụ Igbo"),
            "id" => ("ind", "Indonesia"),
            "ia" => ("ina", "Interlingua"),
            "iu" => ("iku", "ᐃᓄᒃᑎᑐᑦ"),
            "ik" => ("ipk", "Inupiat"),
            "ga" => ("gle", "Gaeilge na hÉireann"),
            "it" => ("ita", "Italiano"),
            "jv" => ("jav", "ꦧꦱꦗꦮ"),
            "kn" => ("kan", "ಕನ್ನಡ"),
            "ks" => ("kas", "कॉशुर"),
            "kk" => ("kaz", "Қазақ тілі"),
            "km" => ("khm", "ភាសាខ្មែរ"),
            "rw" => ("kin", "Ikinyarwanda"),
            "tlh" => ("tlh", "tlhIngan Hol"),
            "ku" => ("kur", "Kurdî"),
            "ky" => ("kir", "кыргыз тили"),
            "lo" => ("lao", "ພາສາລາວ"),
            "la" => ("lat", "latīna"),
            "lv" => ("lav", "latviešu valoda"),
            "ln" => ("lin", "Lingála"),
            "lt" => ("lit", "lietuvių kalba"),
            "lb" => ("ltz", "Lëtzebuergesch"),
            "mk" => ("mac", "Македонски јазик"),
            "mg" => ("mlg", "maa.laa.gaas"),
            "ms" => ("may", "Melayu"),
            "ml" => ("mal", "മലയാളം"),
            "mt" => ("mlt", "Lingwa Maltija"),
            "mi" => ("mao", "Māori"),
            "mr" => ("mar", "मराठी Marāṭhī"),
            "mas" => ("mas", "Maasai"),
            "nan" => ("nan", "閩南語"),
            "nan-TW" => ("nan", "閩南語(台灣)"),
            "lus" => ("lus", "Mizo ṭawng"),
            "mo" => ("mol", "Limba moldovenească"),
            "mn" => ("mon", "монгол хэл"),
            "my" => ("bur", "မြန်မာဘာသာ"),
            "na" => ("nau", "Dorerin Naoero"),
            "nv" => ("nav", "Diné bizaad"),
            "ne" => ("nep", "नेपाली Nepālī"),
            "no" => ("nor", "norsk språk"),
            "fa" => ("per", "فارسی"),
            "fa-AF" => ("per", "فارسی"),
            "fa-IR" => ("per", "فارسی"),
            "pl" => ("pol", "Polski"),
            "pt" => ("por", "Português"),
            "pt-BR" => ("por", "Português(brasil)"),
            "pt-PT" => ("por", "Português(portugal)"),
            "ro" => ("rum", "Română"),
            "ru" => ("rus", "Русский"),
            "ru-Latn" => ("rus", "Русский(фонетический)"),
            "sr" => ("srp", "Српски"),
            "sr-Cyrl" => ("srp", "Српски(ћирилица)"),
            "sr-Latn" => ("srp", "Српски(латиница)"),
            "sh" => ("scr", "srpskohrvatski"),
            "sk" => ("slo", "slovenský"),
            "es" => ("spa", "Español"),
            "es-419" => ("spa", "Español(Latinoamérica)"),
            "es-MX" => ("spa", "Español(México)"),
            "es-ES" => ("spa", "Español(España)"),
            "es-US" => ("spa", "Español(Estados Unidos)"),
            "sv" => ("swe", "Svenska"),
            "tl" => ("tgl", "Tagalog"),
            "th" => ("tha", "ไทย"),
            "tr" => ("tur", "Türkçe"),
            "uk" => ("ukr", "Українська"),
            "ur" => ("urd", "Urdu"),
            "vi" => ("vie", "Tiếng Việt"),
            //太多了，我蚌埠住了，后面懒得查
            //"ie"                => ("", ""),
            //"oc"                => ("",   ""),
            //"or"                => ("",   ""),
            //"om"                => ("",   ""),
            //"ps"                => ("",   ""),
            //"pa"                => ("",   ""),
            //"qu"                => ("",   ""),
            //"rm"                => ("",   ""),
            //"rn"                => ("",   ""),
            //"sm"                => ("",   ""),
            //"sg"                => ("",   ""),
            //"sa"                => ("",   ""),
            //"gd"                => ("",   ""),
            //"sdp"               => ("",   ""),
            //"sn"                => ("",   ""),
            //"scn"               => ("",   ""),
            //"sd"                => ("",   ""),
            //"si"                => ("",   ""),
            //"sl"                => ("",   ""),
            //"so"                => ("",   ""),
            //"st"                => ("",   ""),
            //"su"                => ("",   ""),
            //"sw"                => ("",   ""),
            //"ss"                => ("",   ""),
            //"tg"                => ("",   ""),
            //"ta"                => ("",   ""),
            //"tt"                => ("",   ""),
            //"te"                => ("",   ""),
            //"ti"                => ("",   ""),
            //"to"                => ("",   ""),
            //"ts"                => ("",   ""),
            //"tn"                => ("",   ""),
            //"tk"                => ("",   ""),
            //"tw"                => ("",   ""),
            //"uz"                => ("",   ""),
            //"vo"                => ("",   ""),
            //"cy"                => ("",   ""),
            //"fy"                => ("",   ""),
            //"wo"                => ("",   ""),
            //"xh"                => ("",   ""),
            //"yi"                => ("",   ""),
            //"yo"                => ("",   ""),
            //"zu"                => ("",   ""),
            _ => ("und", "Undetermined")
        };
    }

    #region 字幕接口

    private static async Task<List<Subtitle>?> GetIntlSubtitlesFromApi1Async(string aid, string cid, string epId, int index, CancellationToken token = default)
    {
        try
        {
            List<Subtitle> subtitles = new();
            string api = "https://" + (Config.Current.EpHost == "api.bilibili.com" ? "api.biliintl.com" : Config.Current.EpHost) + $"/intl/gateway/web/v2/subtitle?episode_id={epId}";
            string json = await HTTPUtil.GetWebSourceAsync(api, token: token);
            using var infoJson = JsonDocument.Parse(json);
            var subs = infoJson.RootElement.GetPropertySafe("data").EnumerateArraySafe("subtitles");
            foreach (var sub in subs)
            {
                var lan = sub.GetValueAsStringSafe("lang_key");
                var url = sub.GetValueAsStringSafe("url");
                // 空 URL 的条目无法下载：跳过该条目而不是抛异常。
                // 此前的 ArgumentException 不在本方法 catch 过滤内，会一路抛出并终止整个下载。
                if (string.IsNullOrEmpty(url)) continue;
                Subtitle subtitle = new()
                {
                    url = url,
                    lan = lan,
                    path = BuildSubtitlePath(aid, cid, lan, url.Contains(".json") ? "srt" : "ass")
                };

                subtitles.Add(subtitle);
            }
            return subtitles;
        }
        catch (Exception ex) when (ex is HttpRequestException or JsonException or KeyNotFoundException or TimeoutException)
        {
            Logger.LogDebug("GetIntlSubtitlesFromApi1 failed: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetIntlSubtitlesFromApi2Async(string aid, string cid, string epId, int index, CancellationToken token = default)
    {
        try
        {
            List<Subtitle> subtitles = new();
            string api = "https://" + (Config.Current.Host == "api.bilibili.com" ? "api.bilibili.tv" : Config.Current.Host) +
                         $"/intl/gateway/v2/ogv/view/app/season?ep_id={epId}&platform=android&s_locale=zh_SG" + (Config.Current.Token != "" ? $"&access_key={Config.Current.Token}" : "");
            string json = await HTTPUtil.GetWebSourceAsync(api, token: token);
            using var infoJson = JsonDocument.Parse(json);
            var modules = infoJson.RootElement.GetPropertySafe("result").GetPropertySafe("modules");
            if (modules.GetArrayLength() == 0) return null;
            var episodes = modules[0].GetPropertySafe("data").GetPropertySafe("episodes");
            if (index < 1 || index > episodes.GetArrayLength()) return null;
            var subs = episodes[index - 1].EnumerateArraySafe("subtitles");
            foreach (var sub in subs)
            {
                var lan = sub.GetValueAsStringSafe("key");
                var url = sub.GetValueAsStringSafe("url").Replace("\\\\/", "/");
                // 空 URL 的条目无法下载：跳过该条目而不是抛异常。
                // 此前的 ArgumentException 不在本方法 catch 过滤内，会一路抛出并终止整个下载。
                if (string.IsNullOrEmpty(url)) continue;
                Subtitle subtitle = new()
                {
                    url = url,
                    lan = lan,
                    path = BuildSubtitlePath(aid, cid, lan, url.Contains(".json") ? "srt" : "ass")
                };

                subtitles.Add(subtitle);
            }
            return subtitles;
        }
        catch (Exception ex) when (ex is HttpRequestException or JsonException or KeyNotFoundException or InvalidOperationException or IndexOutOfRangeException or ArgumentException or TimeoutException)
        {
            Logger.LogDebug("GetIntlSubtitlesFromApi2 failed: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromApi1Async(string aid, string cid, string epId, int index, CancellationToken token = default)
    {
        try
        {
            List<Subtitle> subtitles = new();
            string api = $"https://api.bilibili.com/x/web-interface/view?aid={aid}&cid={cid}";
            string json = await HTTPUtil.GetWebSourceAsync(api, token: token);
            using var infoJson = JsonDocument.Parse(json);
            var subs = infoJson.RootElement.GetPropertySafe("data").GetPropertySafe("subtitle").EnumerateArraySafe("list");
            foreach (var sub in subs)
            {
                var lan = sub.GetValueAsStringSafe("lan");
                var subtitleUrl = sub.GetValueAsStringSafe("subtitle_url");
                // 空 URL 的条目无法下载：跳过该条目而不是抛异常（同 GetIntlSubtitlesFromApi2）
                if (string.IsNullOrEmpty(subtitleUrl)) continue;
                Subtitle subtitle = new()
                {
                    url = subtitleUrl,
                    lan = lan,
                    path = BuildSubtitlePath(aid, cid, lan, "srt")
                };

                subtitles.Add(subtitle);
            }

            //无字幕片源 但是字幕没上导致的空列表，尝试从国际接口获取
            //if (subtitles.Count == 0 && !string.IsNullOrEmpty(epId))
            //{
            //    return await GetSubtitlesAsync(aid, cid, epId, true);
            //}
            return subtitles;
        }
        catch (Exception ex) when (ex is HttpRequestException or JsonException or KeyNotFoundException or TimeoutException)
        {
            Logger.LogDebug("GetSubtitlesFromApi1 failed: {0}", ex.Message);
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromApi2Async(string aid, string cid, string epId, int index, CancellationToken token = default)
    {
        try
        {
            List<Subtitle> subtitles = new();
            // 端点名带 wbi：登录态（nav 已取得密钥）下按规范补签名（参数按 key 升序 + wts），
            // 兼容接口未来收紧；未登录（密钥为空）保持无签名——空 key 的 w_rid 必被 -352 拒绝，
            // 现状无签名反而可用（RF-26）。
            string api = !string.IsNullOrEmpty(Config.Current.Wbi)
                ? $"https://api.bilibili.com/x/player/wbi/v2?{Parser.WbiSign($"aid={aid}&cid={cid}&wts={ServerClock.NowUnixSeconds()}")}"
                : $"https://api.bilibili.com/x/player/wbi/v2?cid={cid}&aid={aid}";
            string json = await HTTPUtil.GetWebSourceAsync(api, token: token);
            using var infoJson = JsonDocument.Parse(json);
            var subs = infoJson.RootElement.GetPropertySafe("data").GetPropertySafe("subtitle").EnumerateArraySafe("subtitles");
            foreach (var sub in subs)
            {
                var lan = sub.GetValueAsStringSafe("lan");
                var subtitleUrl = sub.GetValueAsStringSafe("subtitle_url");
                // 空 URL 的条目无法下载：跳过该条目而不是抛异常（同 GetIntlSubtitlesFromApi2）
                if (string.IsNullOrEmpty(subtitleUrl)) continue;
                Subtitle subtitle = new()
                {
                    url = subtitleUrl,
                    lan = lan,
                    path = BuildSubtitlePath(aid, cid, lan, "srt")
                };

                subtitles.Add(subtitle);
            }

            return subtitles;
        }
        catch (Exception ex) when (ex is HttpRequestException or JsonException or KeyNotFoundException or TimeoutException)
        {
            Logger.LogDebug("GetSubtitlesFromApi2 failed: {0}", ex.Message);
            return null;
        }
    }

    private static byte[] GetPayload(long aid, long cid)
    {
        var obj = new DmViewReq
        {
            Pid = aid,
            Oid = cid,
            Type = 1,
            Spmid = "main.ugc-video-detail.0.0",
        };
        return AppHelper.PackMessage(obj.ToByteArray());
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromApi3Async(string aid, string cid, string epId, int index, CancellationToken token = default)
    {
        try
        {
            List<Subtitle> subtitles = new();
            //grpc调用接口 protobuf
            string api = "https://app.biliapi.net/bilibili.community.service.dm.v1.DM/DmView";

            if (!long.TryParse(aid, out var aidLong) || !long.TryParse(cid, out var cidLong))
                return null;
            var data = GetPayload(aidLong, cidLong);

            var t = AppHelper.ReadMessage(await HTTPUtil.GetPostResponseAsync(api, data, token: token));
            var resp = new MessageParser<DmViewReply>(() => new DmViewReply()).ParseFrom(t);

            if (resp.Subtitle != null && resp.Subtitle.Subtitles != null)
            {
                // 空 URL 的条目无法下载：跳过该条目而不是抛异常（同 GetIntlSubtitlesFromApi2）
                subtitles.AddRange(resp.Subtitle.Subtitles
                    .Where(item => !string.IsNullOrEmpty(item.SubtitleUrl))
                    .Select(item => new Subtitle()
                    {
                        url = item.SubtitleUrl,
                        lan = item.Lan,
                        path = BuildSubtitlePath(aid, cid, item.Lan, "srt")
                    }));
            }

            return subtitles;
        }
        catch (Exception ex) when (ex is HttpRequestException or InvalidOperationException or InvalidProtocolBufferException
                              or System.Text.Json.JsonException or InvalidDataException or TimeoutException)
        {
            // JsonException 覆盖 RiskControlResponseException（接口返回 HTML 而非 grpc 数据）：
            // 字幕是装饰性资源，任何抓取失败（含 HTTPUtil 重试耗尽抛出的 TimeoutException）
            // 都应降级为"无字幕"而非让页面下载失败
            Logger.LogDebug("GetSubtitlesFromApi3 failed: {0}", ex.Message);
            return null;
        }
    }

    #endregion

    public static async Task<List<Subtitle>> GetSubtitlesAsync(string aid, string cid, string epId, int index, bool intl, CancellationToken token = default)
    {
        List<Subtitle>? subtitles = new();
        if (intl)
        {
            subtitles = await GetIntlSubtitlesFromApi1Async(aid, cid, epId, index, token) ?? await GetIntlSubtitlesFromApi2Async(aid, cid, epId, index, token);
        }
        else
        {
            if (Config.Current.Cookie == "")
            {
                subtitles = await GetSubtitlesFromApi3Async(aid, cid, epId, index, token); // 未登录只有APP可以拿到字幕了
            }
            else
            {
                subtitles = await GetSubtitlesFromApi2Async(aid, cid, epId, index, token)
                            ?? await GetSubtitlesFromApi1Async(aid, cid, epId, index, token)
                            ?? await GetSubtitlesFromApi3Async(aid, cid, epId, index, token);
            }

        }

        if (subtitles == null)
        {
            return new List<Subtitle>(); //返回空列表
        }

        //修正 url 协议
        foreach (var item in subtitles)
        {
            if (item.url.StartsWith("//")) item.url = "https:" + item.url;
        }

        return subtitles;
    }

    public static async Task SaveSubtitleAsync(string url, string path, CancellationToken token = default)
    {
        if (path.EndsWith(".srt"))
            await File.WriteAllTextAsync(path, ConvertSubFromJson(await HTTPUtil.GetWebSourceAsync(url, token: token)), Encoding.UTF8, token);
        else
            await File.WriteAllTextAsync(path, await HTTPUtil.GetWebSourceAsync(url, token: token), Encoding.UTF8, token);
    }

    private static string ConvertSubFromJson(string jsonString)
    {
        StringBuilder lines = new();
        using var json = JsonDocument.Parse(jsonString);
        var sub = json.RootElement.EnumerateArraySafe("body").ToList();
        for (int i = 0; i < sub.Count; i++)
        {
            var line = sub[i];
            lines.AppendLine((i + 1).ToString());
            lines.AppendLine($"{FormatTime(line.GetDoubleSafe("from"))} --> {FormatTime(line.GetDoubleSafe("to"))}");
            //有的没有内容
            if (line.TryGetProperty("content", out JsonElement content))
                lines.AppendLine(SanitizeSrtContent(content.ToString()));
            lines.AppendLine();
        }
        return lines.ToString();
    }

    /// <summary>
    /// 按 SRT 的 <c>HH:MM:SS,mmm</c> 输出时间轴。
    /// 不能用 <c>hh</c> 格式符：它取的是 TimeSpan.Hours（0-23），
    /// 超过 24 小时的时间会丢掉天数——86400 秒会变成 00:00:00，
    /// 让超长视频的字幕整体跳回开头。SRT 本身允许小时数超过 24。
    /// 负数时间在 SRT 中无意义，夹紧到 0，否则符号会被格式化悄悄丢弃。
    /// </summary>
    internal static string FormatTime(double sec) //64.13
    {
        if (double.IsNaN(sec) || sec < 0) sec = 0;
        // 防御畸形时间值：TimeSpan.FromSeconds 对超出 TimeSpan.MaxValue 的输入抛
        // OverflowException，字幕 JSON 里异常的时间字段不应让格式转换直接崩溃。
        // TotalHours 转 long 而非 int：超长视频的小时数可能超过 int 范围。
        if (sec > TimeSpan.MaxValue.TotalSeconds) sec = TimeSpan.MaxValue.TotalSeconds;
        var ts = TimeSpan.FromSeconds(sec);
        return $"{(long)ts.TotalHours:D2}:{ts.Minutes:D2}:{ts.Seconds:D2},{ts.Milliseconds:D3}";
    }

    /// <summary>
    /// 中和字幕正文里会破坏 SRT 块结构的字符。
    /// SRT 用空行分隔字幕块：正文中一旦出现空行，后续所有字幕都会错位。
    /// 多行正文本身合法，因此只折叠空行而不是删除全部换行。
    /// </summary>
    internal static string SanitizeSrtContent(string? content)
    {
        if (string.IsNullOrEmpty(content)) return string.Empty;

        var normalized = content.Replace("\r\n", "\n").Replace('\r', '\n');
        var keptLines = normalized
            .Split('\n')
            .Select(l => l.TrimEnd())
            .Where(l => l.Length > 0)
            .Select(l => l.Contains("-->") ? l.Replace("-->", "->") : l);

        return string.Join('\n', keptLines);
    }

    [GeneratedRegex(@"-([a-zA-Z0-9]+)")]
    private static partial Regex SubTagRegex();
}
